Repository perfsee/perfsee, pull requests merged in 2022-11, with the labels that each got.

#181 fix: missing coverage if run integration test in container
  .github/workflows/commit.yaml
Labels: test

#183 fix(platform): update environment with same site
  packages/platform-server/src/db/mysql/property.entity.ts
  packages/platform/src/modules/project/settings/settings-environments/env-edit-form.tsx
  packages/platform/src/modules/project/settings/settings-environments/form-cookies.tsx
  packages/platform/src/modules/shared/property-type.ts
  packages/schema/src/graphql/setting/fragments/environment-fields.gql
  packages/schema/src/server-schema.gql
Labels: bug

#162 feat: test whether page config works well before taking snapshots
  db/migrations/1666250880517-job-extra.ts
  packages/platform-server/src/db/mysql/job.entity.ts
  packages/platform-server/src/db/mysql/runner.entity.ts
  packages/platform-server/src/event/index.ts
  packages/platform-server/src/modules/job/service.ts
  packages/platform-server/src/modules/page/resolver.ts
  packages/platform-server/src/modules/page/service.ts
  packages/platform-server/src/modules/page/types.ts
  packages/platform-server/src/modules/snapshot/resolver.ts
  packages/platform-server/src/modules/snapshot/service.ts
  packages/platform-server/src/utils/get-lh-run-data.ts
  packages/platform/src/icons.tsx
  packages/platform/src/modules/project/settings/cards/index.tsx
  packages/platform/src/modules/project/settings/cards/styled.tsx
  packages/platform/src/modules/project/settings/settings-common-comp.tsx
  packages/platform/src/modules/project/settings/settings-e2e/index.tsx
  packages/platform/src/modules/project/settings/settings-environments/index.tsx
  packages/platform/src/modules/project/settings/settings-pages/index.tsx
  packages/platform/src/modules/project/settings/settings-pages/page-list-cell.tsx
  packages/platform/src/modules/project/settings/settings-pages/ping-content.tsx
  packages/platform/src/modules/project/settings/settings-pages/style.tsx
  packages/platform/src/modules/project/settings/settings-pages/temp-list.tsx
  packages/platform/src/modules/project/settings/settings-pages/web.svg
  packages/platform/src/modules/project/settings/settings-profiles/index.tsx
  packages/platform/src/modules/project/settings/style.ts
  packages/platform/src/modules/shared/property.module.ts
  packages/runner/executor/src/local-entry.ts
  packages/runner/lab/src/index.ts
  packages/runner/lab/src/lighthouse/index.ts
  packages/runner/lab/src/lighthouse/ping-worker.ts
  packages/runner/shared/src/worker.ts
  packages/schema/src/graphql/setting/ping-result.gql
  packages/schema/src/graphql/setting/ping.gql
  packages/schema/src/server-schema.gql
  packages/server-common/src/job/index.ts
  packages/server-common/src/types/index.ts
  tools/cli/upload-scripts.ts
Labels: enhancement

#176 feat: allow user to bulk create cookies and header from clipboard
  docs/assets/settings/cookies-stringify.png
  docs/assets/settings/cookies-table.png
  docs/assets/settings/create-environment.png
  docs/assets/settings/edit-environment.png
  docs/assets/settings/environment-competitor.png
  docs/assets/settings/headers-stringify.png
  docs/docs/settings/environment-setting.md
  docs/i18n/cn/docusaurus-plugin-content-docs/current/settings/environment-setting.md
  packages/platform-server/src/db/mysql/property.entity.ts
  packages/platform/src/modules/project/settings/settings-environments/form-cookies.tsx
  packages/platform/src/modules/project/settings/settings-environments/form-headers.tsx
  packages/runner/lab/src/lighthouse/e2e-worker.ts
  packages/runner/lab/src/lighthouse/helpers/utils.ts
  packages/runner/lab/src/lighthouse/lighthouse-worker.ts
  packages/schema/src/server-schema.gql
  packages/shared/src/types/snapshot.ts
Labels: enhancement

#195 fix(platform): wrong MAX/MIN label in competitor RUM comparison table
  packages/components/src/table/index.tsx
  packages/platform/src/modules/competitor/competitor-metrics.tsx
  packages/platform/src/modules/competitor/competitor-table.tsx
Labels: bug
